# Rename this file to CONFIG.yaml and adjust the settings for them to apply
slskd:
  # The URL of your SLSKD server
  HOST: "http://localhost:5300"
  # The API key of your SLSKD server. It should be available in your SLSKD config file
  API_KEY: "somerandomkeyhere"
  # The path to the download folder of SLSKD
  SLSKD_DOWNLOADS: "/path/to/slskd/download/complete/folder"

listenbrainz:
  # The recommendations of the user you wish to get. Must have a public profile.
  USERNAME: "YourUsernameHere"
  # any email address you control
  EMAIL: "example@gmail.com"

beets:
  # if you aren't using beets, keep this false and ignore the other settings in this section
  AUTO_REMOVE_DUPLICATES: false
  # The path to your already imported beets music
  BEETS_IMPORTED: "/path/to/folder/with/imported/beets"
  # The path to your beets config.yaml file
  BEETS_CONFIG: "/path/to/folder/with/beets/config/config.yaml"
  # The path to your beets database file
  BEETS_DATABASE: "/mnt/beets/beets/library.db"
  # The path to a requirements txt file which contains all of the beets modules that need to be installed
  BEETS_REQUIREMENTS: "/mnt/beets/beets/requirements.txt"

soulbrainarr:
  # How long to wait before running the script again
  RUN_INTERVAL_MINUTES: 5
  # The number of songs recommendations to grab each run
  SONG_BATCH_SIZE: 15
